//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by FileRemover.rc
//
#define IDD_DAMAINDIALOG                101
#define IDI_MAIN                        102
#define IDR_TRAYMENU                    104
#define IDC_CHECK_HIDEATSTARTUP         1000
#define IDC_LIST_FILES                  1001
#define IDC_BUTTON_REMOVE               1002
#define IDC_BUTTON_ADDFILE              1003
#define IDC_BUTTON_ADDDIR               1004
#define IDM_TRAYMENU_EXIT               40001
#define IDM_TRAYMENU_SHOW               40002

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        105
#define _APS_NEXT_COMMAND_VALUE         40003
#define _APS_NEXT_CONTROL_VALUE         1005
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
